EXPECTED_MATCH = {
    'match_id': '595491',
    'unique_id': 's:300~l:8328~e:595491~c:595491',
    'match_date': '2022-09-17T19:10Z',
    'venue': 'Estadio Libertadores de America',
    'city': 'Buenos Aires',
    'state': 'Argentina',
    'neutral_site': False,
    'indoor': False,
    'team_1_id': '10',
    'team_1_name': 'Argentina',
    'team_1_abbreviation': 'ARG',
    'team_1_home_away': 'home',
    'team_1_score': '20',
    'team_1_winner': False,
    'team_2_id': '5',
    'team_2_name': 'South Africa',
    'team_2_abbreviation': 'SA',
    'team_2_home_away': 'away',
    'team_2_score': '36',
    'team_2_winner': True,
}
